import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.konek;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author W10RPL
 */
public class kereta extends javax.swing.JFrame {

    /**
     * Creates new form kereta
     */
    public kereta() {
        initComponents();
        nonaktif();
        datatabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jkereta = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jtiket = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        namakereta = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        biaya = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        radioanak = new javax.swing.JRadioButton();
        radiodewasa = new javax.swing.JRadioButton();
        radiolansia = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        txtkembali = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpotongan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtpotongan2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtppn = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();
        btnbersih = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kereta = new javax.swing.JTable();
        button_update = new javax.swing.JButton();
        text_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        button_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Stasiun Dimana Aja");

        jLabel2.setText("Jenis Kereta");

        jkereta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AG001", "BS001", "JE001", " " }));
        jkereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkeretaActionPerformed(evt);
            }
        });

        jLabel3.setText("Jumlah Tiket");

        jtiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtiketActionPerformed(evt);
            }
        });
        jtiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtiketKeyPressed(evt);
            }
        });

        jLabel5.setText("Harga");

        namakereta.setEnabled(false);
        namakereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namakeretaActionPerformed(evt);
            }
        });

        harga.setEnabled(false);

        jLabel4.setText("Nama Kereta");

        jLabel6.setText("Biaya");

        biaya.setEnabled(false);
        biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaActionPerformed(evt);
            }
        });

        jLabel7.setText("Jenis Penumpang");

        buttonGroup1.add(radioanak);
        radioanak.setText("Anak-anak");
        radioanak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioanakActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiodewasa);
        radiodewasa.setText("Dewasa");
        radiodewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiodewasaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiolansia);
        radiolansia.setText("Lansia");
        radiolansia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiolansiaActionPerformed(evt);
            }
        });

        jLabel15.setText("Kembali");

        txtkembali.setEnabled(false);

        jLabel8.setText("Asuransi");

        txtpotongan.setEnabled(false);

        jLabel13.setText("Total");

        txttotal.setEnabled(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        txttotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttotalKeyPressed(evt);
            }
        });

        jLabel14.setText("Bayar");

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        jLabel9.setText("Potongan");

        txtpotongan2.setEnabled(false);

        jLabel10.setText("PPN");

        txtppn.setEnabled(false);

        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        btnbersih.setText("Clear");
        btnbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        tabel_kereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_kereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_keretaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kereta);

        button_update.setText("Update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        text_id.setEditable(false);
        text_id.setEnabled(false);

        jLabel11.setText("ID");

        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioanak)
                                    .addComponent(radiodewasa)
                                    .addComponent(radiolansia)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jtiket, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtpotongan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(biaya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtppn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtpotongan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_id)
                                    .addComponent(jkereta, 0, 127, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(txtkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txttotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(harga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(namakereta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                            .addComponent(button_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnbersih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(button_update, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                            .addComponent(btnkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(btnproses))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jkereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioanak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(radiodewasa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radiolansia)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtpotongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtpotongan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namakereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnproses)
                            .addComponent(button_update))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_delete)
                            .addComponent(btnbersih))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnkeluar)
                        .addComponent(button_save))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datatabel(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("Jenis Kereta");
        tbl.addColumn("Jumlah Tiket");
        tbl.addColumn("Nama Kereta");
        tbl.addColumn("Biaya");
        tabel_kereta.setModel(tbl);
        
        try{
            Statement input = (Statement) konek.getConnection().createStatement();
            ResultSet res = input.executeQuery("SELECT * FROM kereta");
            while(res.next())
            {
                tbl.addRow(new Object[] {
                res.getString("id"),
                res.getString("jenis"),
                res.getString("jumlah"),        
                res.getString("nama"),
                res.getString("biaya"),
                }
                );
                tabel_kereta.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    private void namakeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namakeretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namakeretaActionPerformed

    private void jkeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkeretaActionPerformed
        // TODO add your handling code here:
        if(jkereta.getSelectedItem() == "AG001"){
            namakereta.setText("ARGO BROMO");
            harga.setText("1000000");
        }else if(jkereta.getSelectedItem() == "BS001"){
            namakereta.setText("BIMASAKTI");
            harga.setText("2000000");
        }else if(jkereta.getSelectedItem() == "JE001"){
            namakereta.setText("JAKARTA EXPRESS");
            harga.setText("3000000");
        }
        jtiket.requestFocus();
    }//GEN-LAST:event_jkeretaActionPerformed

    private void jtiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtiketActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtiketActionPerformed

    private void biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biayaActionPerformed

    private void jtiketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtiketKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() != 10) {
            return;
        }
        int hargaa = Integer.parseInt(String.valueOf(harga.getText()));
        int tiket = Integer.parseInt(String.valueOf(jtiket.getText()));
        int hasil = hargaa * tiket;
        biaya.setText(String.valueOf(hasil));
        aktif();
    }//GEN-LAST:event_jtiketKeyPressed

    private void radioanakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioanakActionPerformed
        // TODO add your handling code here:
        radiobutton();
    }//GEN-LAST:event_radioanakActionPerformed

    private void radiodewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiodewasaActionPerformed
        // TODO add your handling code here:
        radiobutton();
    }//GEN-LAST:event_radiodewasaActionPerformed

    private void radiolansiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiolansiaActionPerformed
        // TODO add your handling code here:
        radiobutton();
    }//GEN-LAST:event_radiolansiaActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txttotalActionPerformed

    private void txttotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txttotalKeyPressed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(String.valueOf(txttotal.getText()));
        int bayarr = Integer.parseInt(String.valueOf(bayar.getText()));
        int hasil = bayarr - total;
        txtkembali.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnprosesActionPerformed

    private void btnbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnbersihActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO kereta(jenis,jumlah,nama,biaya) VALUES ('"+jkereta.getSelectedItem()+"','"+jtiket.getText()+"','"+namakereta.getText()+"','"+biaya.getText()+"')";
            java.sql.Connection conn=(Connection)koneksi.konek.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        clear();
    }//GEN-LAST:event_button_saveActionPerformed

    private void tabel_keretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_keretaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel_kereta.getModel();
        tabel_kereta.getSelectedRow();
        
        Object id_penyewa = model.getValueAt(tabel_kereta.getSelectedRow(),0);
        text_id.setText(String.valueOf(id_penyewa));
        
        Object jenis_kereta = model.getValueAt(tabel_kereta.getSelectedRow(),1);
        jkereta.setSelectedItem(String.valueOf(jenis_kereta));

        Object jumlah_tiket = model.getValueAt(tabel_kereta.getSelectedRow(),2);
        jtiket.setText(String.valueOf(jumlah_tiket));
        
        Object nama_kereta = model.getValueAt(tabel_kereta.getSelectedRow(),3);
        namakereta.setText(String.valueOf(nama_kereta));

        Object biaya_kereta = model.getValueAt(tabel_kereta.getSelectedRow(),4);
        biaya.setText(String.valueOf(biaya_kereta));

        button_update.setEnabled(true);
        button_delete.setEnabled(true);
        button_save.setEnabled(false);
    }//GEN-LAST:event_tabel_keretaMouseClicked

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:
        if(button_update.getText()=="bedit"){
            text_id.requestFocus();
        }else{
            String id_penyewa = text_id.getText();
            String jenis_kereta = (String) jkereta.getSelectedItem();
            String jumlah_tiket = jtiket.getText();
            String nama_kereta = namakereta.getText();
            String biaya_kereta = biaya.getText();
            String hargaa = harga.getText();
            String total = txttotal.getText();
            String bayarr = bayar.getText();
            String kembali = txtkembali.getText();
            try{
                Statement statement = (Statement) konek.getConnection().createStatement();
                statement.executeUpdate("UPDATE kereta SET jenis='"+jenis_kereta+"', jumlah='"+jumlah_tiket+"', nama='"+nama_kereta+"', biaya='"+biaya_kereta+"'"+" WHERE id='"+id_penyewa+"' ");
                JOptionPane.showMessageDialog(null, "Data berhasil di Update");
                clear();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal di Update"+ e.getMessage());
            }
            datatabel();
        }
    }//GEN-LAST:event_button_updateActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
        String id_penyewa = text_id.getText();
        String jenis_kereta = (String) jkereta.getSelectedItem();
        String jumlah_tiket = jtiket.getText();
        String nama_kereta = namakereta.getText();
        String biaya_kereta = biaya.getText();
        String hargaa = harga.getText();
        String total = txttotal.getText();
        String bayarr = bayar.getText();
        String kembali = txtkembali.getText();
        try{
            Statement statement = (Statement) konek.getConnection().createStatement();
            statement.executeUpdate("DELETE FROM kereta  WHERE id='"+id_penyewa+"' ");
            JOptionPane.showMessageDialog(null, "Berhasil menghapus Data!");
            statement.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal menghapus Data!"+ e.getMessage());
        }
        datatabel();
        clear();
    }//GEN-LAST:event_button_deleteActionPerformed
    private void clear(){
        jtiket.setText("");
        namakereta.setText("");
        harga.setText("");
        biaya.setText("");
        txtpotongan2.setText("");
        txtppn.setText("");
        txtpotongan.setText("");
        txttotal.setText("");
        txttotal.setText("");
        bayar.setText("");
        txtkembali.setText("");
        radioanak.setSelected(false);
        radiodewasa.setSelected(false);
        radiolansia.setSelected(false);
        buttonGroup1.clearSelection();
        datatabel();
        nonaktif();
    }
    private void radiobutton(){
    if(radioanak.isSelected()){
    radiodewasa.setSelected(false);
    radiolansia.setSelected(false);
    int potongan = Integer.parseInt(String.valueOf(biaya.getText()));
    int persen = (int)((0.15)*potongan);
    txtpotongan.setText(String.valueOf(persen));
    }
    else if(radiodewasa.isSelected()){
    radioanak.setSelected(false);
    radiolansia.setSelected(false);
    int potongan = Integer.parseInt(String.valueOf(biaya.getText()));
    int persen = (int)((0.10)*potongan);
    txtpotongan.setText(String.valueOf(persen));
    }
    else if(radiolansia.isSelected()){
    radioanak.setSelected(false);
    radiodewasa.setSelected(false);
    int potongan = Integer.parseInt(String.valueOf(biaya.getText()));
    int persen = (int)((0.05)*potongan);
    txtpotongan.setText(String.valueOf(persen));
    }
    bayar.requestFocus();
    
    int asuransi = Integer.parseInt(String.valueOf(txtpotongan.getText()));
    int biayaaa = Integer.parseInt(String.valueOf(biaya.getText()));
    int potongan = biayaaa - asuransi;
    txtpotongan2.setText(String.valueOf(potongan));
    
    int pajak = Integer.parseInt(String.valueOf(biaya.getText()));
    int ppn = (int)((0.10)*pajak);
    txtppn.setText(String.valueOf(ppn));
    
    int potongan2 = Integer.parseInt(String.valueOf(txtpotongan2.getText()));
    int ppn2 = Integer.parseInt(String.valueOf(txtppn.getText()));
    int total = potongan2 + ppn2;
    txttotal.setText(String.valueOf(total));
    
    }
//    private void fasilitas(){
//    if(cekinternet.isSelected()==true&&cekkonsumsi.isSelected()==false){
//        txtbiayafasilitas.setText("10000");
//    }else if(cekinternet.isSelected()==false&&cekkonsumsi.isSelected()==true){
//        txtbiayafasilitas.setText("20000");
//    }else if(cekinternet.isSelected()==true&&cekkonsumsi.isSelected()==true){
//        txtbiayafasilitas.setText("30000");
//    }else{
//        txtbiayafasilitas.setText("0");
//    }
//    int potongan2 = Integer.parseInt(String.valueOf(txtpotongan2.getText()));
//    int ppn2 = Integer.parseInt(String.valueOf(txtppn.getText()));
//    int fasilitas = Integer.parseInt(String.valueOf(txtbiayafasilitas.getText()));
//    int total = potongan2 + ppn2 + fasilitas;
//    txttotal.setText(String.valueOf(total));
//    }
    private void nonaktif(){
    radioanak.setEnabled(false);
    radiodewasa.setEnabled(false);
    radiolansia.setEnabled(false);
}
    private void aktif(){
    radioanak.setEnabled(true);
    radiodewasa.setEnabled(true);
    radiolansia.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kereta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kereta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField biaya;
    private javax.swing.JButton btnbersih;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnproses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_update;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jkereta;
    private javax.swing.JTextField jtiket;
    private javax.swing.JTextField namakereta;
    private javax.swing.JRadioButton radioanak;
    private javax.swing.JRadioButton radiodewasa;
    private javax.swing.JRadioButton radiolansia;
    private javax.swing.JTable tabel_kereta;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField txtkembali;
    private javax.swing.JTextField txtpotongan;
    private javax.swing.JTextField txtpotongan2;
    private javax.swing.JTextField txtppn;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
