import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Dictionary;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import koneksi.konek;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;

/**
 *
 * @author W10RPL
 */
public class kursus extends javax.swing.JFrame {

    /**
     * Creates new form kursus
     */
    public kursus() {
        initComponents();
        datatabel();
        button_delete.setEnabled(false);
        button_update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        text_biayakhursus = new javax.swing.JTextField();
        text_nama = new javax.swing.JTextField();
        text_biayafasilitas = new javax.swing.JTextField();
        text_totalbayar = new javax.swing.JTextField();
        combo_hari = new javax.swing.JComboBox();
        radio_pagi = new javax.swing.JRadioButton();
        combo_jeniskhursus = new javax.swing.JComboBox();
        check_konsumsi = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        button_keluar = new javax.swing.JButton();
        button_bersih = new javax.swing.JButton();
        button_proses = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        radio_malam = new javax.swing.JRadioButton();
        button_update = new javax.swing.JButton();
        check_internet = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        button_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_komputer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Biaya Khursus");

        jLabel10.setText("Total Bayar");

        text_biayakhursus.setEnabled(false);

        text_nama.setEnabled(false);

        text_biayafasilitas.setEnabled(false);

        text_totalbayar.setEnabled(false);

        combo_hari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        combo_hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_hariActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_pagi);
        radio_pagi.setText("Pagi");
        radio_pagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_pagiActionPerformed(evt);
            }
        });

        combo_jeniskhursus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Jenis Khursus", "U001", "P001" }));
        combo_jeniskhursus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jeniskhursusActionPerformed(evt);
            }
        });

        check_konsumsi.setText("Konsumsi");
        check_konsumsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_konsumsiActionPerformed(evt);
            }
        });

        jLabel1.setText("No Pendaftaran ");

        text_id.setEditable(false);
        text_id.setEnabled(false);
        text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idActionPerformed(evt);
            }
        });

        button_keluar.setText("Keluar");
        button_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_keluarActionPerformed(evt);
            }
        });

        button_bersih.setText("Clear");
        button_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bersihActionPerformed(evt);
            }
        });

        button_proses.setText("Proses");
        button_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_prosesActionPerformed(evt);
            }
        });

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_malam);
        radio_malam.setText("Malam");
        radio_malam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_malamActionPerformed(evt);
            }
        });

        button_update.setText("Update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        check_internet.setText("Internet");
        check_internet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_internetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("KHURSUS KOMPUTER");

        jLabel3.setText("Jenis Khursus");

        jLabel4.setText("Waktu Khursus");

        jLabel5.setText("Nama Khursus");

        jLabel6.setText("Beberapa Hari");

        jLabel7.setText("Biaya Fasilitas");

        jLabel8.setText("Fasilitas");

        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        tabel_komputer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_komputer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_komputerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_komputer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radio_pagi)
                        .addGap(26, 26, 26)
                        .addComponent(radio_malam))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check_internet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(check_konsumsi))
                    .addComponent(combo_hari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text_nama)
                    .addComponent(combo_jeniskhursus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text_id))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_biayakhursus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_biayafasilitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(text_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(button_proses, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(70, 70, 70)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(button_update, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(button_save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(button_keluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))))))
                        .addGap(21, 21, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(combo_jeniskhursus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(text_biayakhursus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(text_biayafasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(text_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(radio_pagi)
                            .addComponent(radio_malam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(combo_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(check_internet)
                            .addComponent(check_konsumsi)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_update)
                            .addComponent(button_delete))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_save)
                            .addComponent(button_proses))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_bersih)
                    .addComponent(button_keluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datatabel(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Nomor Pendaftaran");
        tbl.addColumn("Jenis Khursus");
        tbl.addColumn("Nama Khursus");
        tbl.addColumn("Hari");
        tbl.addColumn("Total Bayar");
        tabel_komputer.setModel(tbl);
        
        try{
            Statement input = (Statement) konek.getConnection().createStatement();
            ResultSet res = input.executeQuery("SELECT * FROM kursus");
            while(res.next())
            {
                tbl.addRow(new Object[] {
                res.getString("nomorp"),
                res.getString("jenis"),
                res.getString("nama"),        
                res.getString("hari"),
                res.getString("total"),
                }
                );
                tabel_komputer.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    private void combo_hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_hariActionPerformed
        // TODO add your handling code here:
        int waktukursus = 0;
        if(radio_pagi.isSelected() && combo_jeniskhursus.getSelectedItem()== "U001"){
            radio_malam.setSelected(false);
            waktukursus=50000;
        }else if(radio_pagi.isSelected() && combo_jeniskhursus.getSelectedItem()== "P001"){
            radio_malam.setSelected(false);
            waktukursus=10000;
        }else if(radio_malam.isSelected() && combo_jeniskhursus.getSelectedItem()== "U001"){
            radio_pagi.setSelected(false);
            waktukursus=70000;
        }else if(radio_malam.isSelected() && combo_jeniskhursus.getSelectedItem()== "P001"){
            radio_pagi.setSelected(false);
            waktukursus=120000;
        }

        int hari = Integer.parseInt(String.valueOf(combo_hari.getSelectedItem()));
        int total = waktukursus * hari;
        text_biayakhursus.setText(String.valueOf(total));

        checkbox();

    }//GEN-LAST:event_combo_hariActionPerformed

    private void radio_pagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_pagiActionPerformed
        // TODO add your handling code here:
        radiobutton();
    }//GEN-LAST:event_radio_pagiActionPerformed

    private void combo_jeniskhursusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jeniskhursusActionPerformed
        // TODO add your handling code here:
        if(combo_jeniskhursus.getSelectedItem() == "U001"){
            text_nama.setText("Umum");
        }else{
            text_nama.setText("Private");
        }
        radiobutton();
    }//GEN-LAST:event_combo_jeniskhursusActionPerformed

    private void check_konsumsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_konsumsiActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_check_konsumsiActionPerformed

    private void button_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_keluarActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Anda ingin Keluar ?", "Ya",JOptionPane.YES_NO_OPTION);
        if(exit == JOptionPane.YES_NO_OPTION){
            this.hide();
            new menu().show();
        }
    }//GEN-LAST:event_button_keluarActionPerformed

    private void button_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bersihActionPerformed
        // TODO add your handling code here:
        clear();

    }//GEN-LAST:event_button_bersihActionPerformed

    private void button_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_prosesActionPerformed
        // TODO add your handling code here:
        int biaya1 = Integer.parseInt(String.valueOf(text_biayakhursus.getText()));
        int biaya2 = Integer.parseInt(String.valueOf(text_biayafasilitas.getText()));
        int total = biaya1 + biaya2;
        text_totalbayar.setText(String.valueOf(total));
    }//GEN-LAST:event_button_prosesActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO kursus(nomorp, jenis,nama,hari,total) VALUES (NULL, '"+combo_jeniskhursus.getSelectedItem()+"','"+text_nama.getText()+"','"+combo_hari.getSelectedItem()+"','"+text_totalbayar.getText()+"')";
            //String sql = "INSERT INTO `kursus` (`nomorp`, `jenis`, `nama`, `hari`, `total`) VALUES (NULL, 'U001', 'apa', '1', '21323')";
            java.sql.Connection conn=(Connection)koneksi.konek.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        text_biayafasilitas.setText("");
        datatabel();
        clear();
    }//GEN-LAST:event_button_saveActionPerformed

    private void radio_malamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_malamActionPerformed
        // TODO add your handling code here:
        radiobutton();
    }//GEN-LAST:event_radio_malamActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:
        if(button_update.getText()== "bedit"){
            text_id.requestFocus();
        }else{
            String id_kursus = text_id.getText();
            String jenis_kursus = (String) combo_jeniskhursus.getSelectedItem();
            String nama_kursus = text_nama.getText();
            String hari = (String) combo_hari.getSelectedItem();
            String biaya_kursus = text_biayakhursus.getText();
            String total_pembayaran = text_totalbayar.getText();
            try{
                Statement statement = (Statement) konek.getConnection().createStatement();
                statement.executeUpdate("UPDATE kursus SET jenis='"+jenis_kursus+"', nama='"+nama_kursus+"', hari='"+hari+"', total='"+biaya_kursus+"'"+" WHERE nomorp='"+id_kursus+"' ");
                JOptionPane.showMessageDialog(null, "Data berhasil di Update");
                clear();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal di Update"+ e.getMessage());
            }
            datatabel();
            clear();
        }
    }//GEN-LAST:event_button_updateActionPerformed

    private void check_internetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_internetActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_check_internetActionPerformed

    private void text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
        String id_kursus = text_id.getText();
        String jenis_kursus = (String) combo_jeniskhursus.getSelectedItem();
        String nama_kursus = text_nama.getText();
        String hari = (String) combo_hari.getSelectedItem();
        String total_pembayaran = text_totalbayar.getText();
        try{
                Statement statement = (Statement) konek.getConnection().createStatement();
                statement.executeUpdate("DELETE FROM kursus  WHERE nomorp='"+id_kursus+"' ");
                JOptionPane.showMessageDialog(null, "Berhasil menghapus Data");
                statement.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Gagal menghapus Data"+ e.getMessage());
            }
        datatabel();
        clear();
    }//GEN-LAST:event_button_deleteActionPerformed

    private void tabel_komputerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_komputerMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel_komputer.getModel();
        tabel_komputer.getSelectedRow();

        Object id_kursusObject = model.getValueAt(tabel_komputer.getSelectedRow(),0);
        text_id.setText(String.valueOf(id_kursusObject));

        Object jenis_khursus = model.getValueAt(tabel_komputer.getSelectedRow(),1 );
        combo_jeniskhursus.setSelectedItem(String.valueOf(jenis_khursus));

        Object nama_kursus = model.getValueAt(tabel_komputer.getSelectedRow(),2);
        text_nama.setText(String.valueOf(nama_kursus));

        Object hari = model.getValueAt(tabel_komputer.getSelectedRow(),3);
        combo_hari.setSelectedItem(String.valueOf(hari));

        Object total_pembayaran = model.getValueAt(tabel_komputer.getSelectedRow(),4);
        text_totalbayar.setText(String.valueOf(total_pembayaran));

        button_save.setEnabled(false);
        button_update.setEnabled(true);
        button_delete.setEnabled(true);
    }//GEN-LAST:event_tabel_komputerMouseClicked
    private void clear(){
        buttonGroup1.clearSelection();  
        text_id.requestFocus();
        text_nama.setText("");
        text_biayakhursus.setText("");
        text_biayafasilitas.setText("");
        text_totalbayar.setText("");
        text_id.setText("");
        combo_hari.setSelectedIndex(0);
        combo_jeniskhursus.setSelectedIndex(0);
        check_internet.setSelected(false);
        check_konsumsi.setSelected(false);
        button_save.setEnabled(true);
        button_update.setEnabled(false);
        button_delete.setEnabled(false);
    }
    
    private void checkbox(){
        if(check_internet.isSelected()== true && check_konsumsi.isSelected()== false){
            text_biayafasilitas.setText("20000");
        }else if(check_konsumsi.isSelected()== true && check_internet.isSelected()== false){
             text_biayafasilitas.setText("50000");
        }else if(check_internet.isSelected()== true && check_konsumsi.isSelected()== true){
            text_biayafasilitas.setText("70000");
        }else{
            text_biayafasilitas.setText("0");
        }
    }
    
    private  void radiobutton(){
       if(radio_pagi.isSelected() && combo_jeniskhursus.getSelectedItem()== "U001"){
           radio_malam.setSelected(false);
           text_biayakhursus.setText("50000");
       }else if(radio_pagi.isSelected() && combo_jeniskhursus.getSelectedItem()== "P001"){
           radio_malam.setSelected(false);
           text_biayakhursus.setText("70000");  
        }else if(radio_malam.isSelected() && combo_jeniskhursus.getSelectedItem()== "U001"){
           radio_pagi.setSelected(false);
           text_biayakhursus.setText("100000");
        }else if(radio_malam.isSelected() && combo_jeniskhursus.getSelectedItem()== "P001"){
           radio_pagi.setSelected(false);
           text_biayakhursus.setText("120000");
        }
         
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kursus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kursus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kursus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kursus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kursus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_bersih;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_keluar;
    private javax.swing.JButton button_proses;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_update;
    private javax.swing.JCheckBox check_internet;
    private javax.swing.JCheckBox check_konsumsi;
    private javax.swing.JComboBox combo_hari;
    private javax.swing.JComboBox combo_jeniskhursus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radio_malam;
    private javax.swing.JRadioButton radio_pagi;
    private javax.swing.JTable tabel_komputer;
    private javax.swing.JTextField text_biayafasilitas;
    private javax.swing.JTextField text_biayakhursus;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_totalbayar;
    // End of variables declaration//GEN-END:variables
}
